#!/usr/bin/env python
# -*- coding: utf-8 -*-

import rospy
import numpy as np
from std_msgs.msg import Float64
from geometry_msgs.msg import Twist

class testfile():
    def __init__(self):
        self.pub_tunnel = rospy.Publisher('/tunnel', Float64, queue_size = 1)

        self.test()

    def test(self):
        rospy.loginfo('publish test')
        self.pub_tunnel.publish(1)


    def main(self):
        rospy.spin()

if __name__ == '__main__':
    rospy.init_node('testfile')
    node = testfile()
    node.main()

