#!/usr/bin/env python
# -*- coding: utf-8 -*-

################################################################################
# Copyright 2018 ROBOTIS CO., LTD.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

# Author: Leon Jung, Gilbert
 
import rospy
import numpy as np
from std_msgs.msg import Float64
from geometry_msgs.msg import Twist

class ControlLane():
    def __init__(self):
        self.sub_lane = rospy.Subscriber('/control/lane', Float64, self.cbFollowLane, queue_size = 1)
        self.sub_max_vel = rospy.Subscriber('/control/max_vel', Float64, self.cbGetMaxVel, queue_size = 1)
        self.pub_cmd_vel = rospy.Publisher('/control/cmd_vel', Twist, queue_size = 1)

        self.lastError = 0
       # self.MAX_VEL = 0.12
        self.MAX_VEL = 0.10
        self.Stop_vel = False
        self.Stop_count = 0 
        rospy.on_shutdown(self.fnShutDown)

    def cbGetMaxVel(self, max_vel_msg):
        self.MAX_VEL = max_vel_msg.data
        #detected RED
        if self.MAX_VEL == 0.0:
            self.Stop_vel = True
            self.Stop_count = 0
        #detected YELLOW
        elif self.MAX_VEL == 0.06:
            self.Stop_vel = True
            self.Stop_count = 1

        elif self.MAX_VEL > 0.06:
              self.Stop_vel = False

    def cbFollowLane(self, desired_center):
        center = desired_center.data

        error = center - 500

        Kp = 0.0025
        Kd = 0.007

        angular_z = Kp * error + Kd * (error - self.lastError)
        self.lastError = error
        twist = Twist()
        twist.linear.x = min(self.MAX_VEL * ((1 - abs(error) / 500) ** 2.2), 0.2)
       # rospy.loginfo(twist.linear.x)
        twist.linear.y = 0
        twist.linear.z = 0
        twist.angular.x = 0
        twist.angular.y = 0
##
        if self.Stop_vel == False:
            twist.angular.z = -max(angular_z, -2.0) if angular_z < 0 else -min(angular_z, 2.0)
           # rospy.loginfo("% False value %")
           # rospy.loginfo(twist.angular.z)
        elif self.Stop_vel == True and self.Stop_count == 0:
             # while self.Stop_count < 10:

              #     twist.angular.z = -min(angular_z, 2.0)
              #     self.Stop_count = self.Stop_count + 1
              #     rospy.loginfo("@@@@@@@@@@@@@@@@@@@@@@ ")
              #     rospy.loginfo(twist.angular.z)
       
#              twist.angular.z = -0.3
#              twist.angular.z = -0.3

             # rospy.loginfo("======================== ")
             # rospy.loginfo(twist.angular.z)

              twist.angular.z = 0
              rospy.loginfo(" ===================== ")
              rospy.loginfo(twist.angular.z)
              self.Stop_count = 2
            
        elif self.Stop_vel == True and self.Stop_count == 1:
              twist.angular.z = 0
             # rospy.loginfo(twist.angular.z)
              self.Stop_count = 2

        self.pub_cmd_vel.publish(twist)

    def fnShutDown(self):
        rospy.loginfo("Shutting down. cmd_vel will be 0")

        twist = Twist()
        twist.linear.x = 0
        twist.linear.y = 0
        twist.linear.z = 0
        twist.angular.x = 0
        twist.angular.y = 0
        twist.angular.z = 0
        self.pub_cmd_vel.publish(twist) 

    def main(self):
        rospy.spin()

if __name__ == '__main__':
    rospy.init_node('control_lane')
    node = ControlLane()
    node.main()
